Deployed Uniswap app, ID: 81ow3i7lnhnivs9
ovrclk/awesome-akash pull request #20
Opened 2020-12-07 23:18 UTC by davaymne

Deployed Uniswap app, ID: 81ow3i7lnhnivs9
http://mt60bmuka993hbirvq0fis7ubk.provider4.akashdev.net/#/swap

{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "mt60bmuka993hbirvq0fis7ubk.provider4.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

2020-12-07 23:22 UTC, davaymne commented
<img width="1723" alt="Screenshot 2020-12-07 at 23 20 49" src="https://user-images.githubusercontent.com/29555611/101417038-f5a61a00-38e2-11eb-9d30-03bc833d2788.png">

2020-12-07 23:26 UTC, boz commented
@davaymne, please read the instructions and look at the other entries.

Did you deploy an sdl from the entry that is already [here](https://github.com/ovrclk/awesome-akash/tree/master/uniswap) for uniswap?

2020-12-08 00:18 UTC, davaymne commented
> @davaymne, please read the instructions and look at the other entries.
> 
> Did you deploy an sdl from the entry that is already [here](https://github.com/ovrclk/awesome-akash/tree/master/uniswap) for uniswap?
yes, I deployed from SDL which is in the list.
I followed with Open-ended Deployments (Deployed an application from the Awesome Akash List). Should I PR any other way?

2020-12-08 00:19 UTC, davaymne commented
<img width="1723" alt="Screenshot 2020-12-08 at 00 18 53" src="https://user-images.githubusercontent.com/29555611/101420889-0bb7d880-38eb-11eb-8061-10909d13f576.png">

2020-12-08 01:41 UTC, davaymne commented
<img width="757" alt="Screenshot 2020-12-08 at 01 17 46" src="https://user-images.githubusercontent.com/29555611/101424658-3ad24800-38f3-11eb-8f61-566aa89f13b2.png">

2020-12-08 02:04 UTC, boz requested changes
Please see #19 , #22 for what is required in the PR.

2020-12-08 02:04 UTC, boz commented on README.md
> +
This should not be here.

2020-12-08 02:04 UTC, boz commented on uniswap/81ow3i7lnhnivs9.json
> +{"lease_id":{"owner":"akash12myahmse3l8cqr2tl9dl2n6vgsnmlcanw6l9er","dseq":"146505","gseq":1,"oseq":1,"provider":"akash174hxdpuxsuys9qkauaf57ym5j8dm4secnz6jd7"},"state":"active","price":{"denom":"uak
This file should not be here.

2020-12-08 03:16 UTC, merged